annport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from wedding import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wedding/', include('wedding.urls')),
    path('', views.wedding_index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedding/urls.py
from django.urls import path
from . import views

app_name = 'wedding'
urlpatterns = [
    path('', views.wedding_index, name='wedding_index'),
    path('service/', views.wedding_service, name='wedding_service'),
    path('detail/<int:mc_id>/', views.wedding_detail, name='wedding_detail'),
    path('list/', views.wedding_list, name='wedding_list'),
    path('cast/', views.wedding_cast, name='wedding_cast'),
    path('cast/success/', views.wedding_cast_success, name='wedding_cast_success'),
    path('partners/etland/', views.partners, name='partners')
]

wedding/models.py
from django.db import models
from taggit.managers import TaggableManager
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)


backdrop_path = PathAndRename('wedding/profile_backdrop/')
mc_path = PathAndRename('wedding/profile_photo/')
gallery_path = PathAndRename('wedding/gallery/')
homepage_path = PathAndRename('wedding/homepage/')


class Backdrops(models.Model):
    image = ProcessedImageField(verbose_name='배경사진',
                                upload_to=backdrop_path,
                                processors=[ResizeToFit(1200, 1200)],
                                format='JPEG',
                                options={'quality': 80})
    backdrop_name = models.CharField('배경이미지제목', max_length=50, blank=True)

    def __str__(self):
        return self.backdrop_name


class Mc(models.Model):
    name = models.CharField('이름', max_length=10)
    title = models.CharField('호칭', max_length=20)
    tags = TaggableManager()
    description = models.TextField('설명')
    profile_photo = models.ImageField('프로필사진', upload_to=mc_path)
    profile_backdrop = models.ForeignKey(Backdrops, on_delete=models.SET_NULL, null=True)
    profile = models.TextField('프로필', blank=True)
    mcdisplay = models.BooleanField('홈페이지노출여부', default=True)
    mcmain = models.BooleanField('메인사회자', default=False)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    wedding_mc = models.ForeignKey(Mc, on_delete=models.CASCADE)
    image = ProcessedImageField(verbose_name='사회자사진',
                                upload_to=gallery_path,
                                processors=[ResizeToFit(1700, 1700)],
                                format='JPEG',
                                options={'quality': 80})


class Youtube(models.Model):
    wedding_mc = models.ForeignKey(Mc, on_delete=models.CASCADE)
    url = models.CharField('유튜브일련번호', max_length=20)


class Cast(models.Model):
    bride = models.CharField('신부님 성함', max_length=20, blank=True)
    groom = models.CharField('신랑님 성함', max_length=20, blank=True)
    bride_phone = models.CharField('신부님 연락처', max_length=20, blank=True)
    groom_phone = models.CharField('신랑님 연락처', max_length=20, blank=True)
    wedding_date = models.CharField('본식 날짜,시간', max_length=100, null=True, blank=True)
    wedding_place = models.CharField('본식 장소', max_length=50, blank=True)
    officiator = models.BooleanField('주례', default=False)
    wedding_reception = models.BooleanField('2부 진행', default=False)
    email_addr = models.EmailField('메일주소', blank=True)
    wish_mc = models.CharField('희망 사회자', max_length=100, blank=True)
    customer_memo = models.TextField('고객 메모', blank=True)
    staff_memo = models.TextField('스탭 메모', blank=True)
    create_date = models.DateTimeField('문의시간')


class Homepage(models.Model):
    title = models.TextField('타이틀', blank=True)
    sub_title = models.TextField('서브타이틀', blank=True)
    description = models.TextField('설명', blank=True)
    buttons_text = models.CharField('버튼글씨', max_length=50, blank=True)
    buttons_url = models.URLField('버튼주소', blank=True)

    main_backdrop = ProcessedImageField(verbose_name='홈사진',
                                        upload_to=homepage_path,
                                        processors=[ResizeToFit(2000, 2000)],
                                        format='JPEG',
                                        options={'quality': 60})
    title_color = models.CharField('타이틀글자색상(hex)', max_length=10, blank=True)
    text_color_dark = models.BooleanField('검은or하얀글자', default=True)
    back_panel = models.BooleanField('반투명배경', default=False)

    display_main = models.BooleanField('메인에 표시', default=True)
    display_priority = models.IntegerField('메인 표시 우선순위', default=10)

wedding/forms.py
from django import forms
from wedding.models import Cast


class CastForm(forms.ModelForm):
    class Meta:
        model = Cast
        fields = ['bride', 'groom', 'bride_phone', 'groom_phone',
                  'wedding_date', 'wedding_place', 'wedding_reception',
                  'officiator',
                  'email_addr', 'wish_mc', 'customer_memo']
        # staff_memo 및 create_date는 view에서 처리함

wedding/views.py
from random import shuffle

from django.shortcuts import render, get_object_or_404, redirect
from wedding.models import Mc, Homepage
from taggit.models import Tag
# from random import shuffle
from .forms import CastForm
from django.utils import timezone


def wedding_index(request):
    homepage = Homepage.objects.exclude(display_main=False).distinct()
    homepage = homepage.order_by('display_priority')
    context = {
        'homepage': homepage
    }
    return render(request, 'wedding/home.html', context)

def wedding_service(request):
    return render(request, 'wedding/wedding_service.html')

def wedding_detail(request, mc_id):
    mc = get_object_or_404(Mc, pk=mc_id)
    tag_list = list(mc.tags.all())
    context = {'mc': mc, 'tag_list': tag_list}
    return render(request, 'wedding/mc_detail.html', context)


def wedding_list(request):
    mc_search_name = request.GET.get('mc_search_name', '')
    mc_search_tag = request.GET.get('mc_search_tag', '')
    mclist0 = Mc.objects.exclude(mcdisplay=False).order_by('-mcmain', '?').distinct()
    if mc_search_name:
        mclist0 = mclist0.filter(name__icontains=mc_search_name).order_by().distinct()
    if mc_search_tag:
        mc_search_tag_list = [tag.strip() for tag in mc_search_tag.split(',')]
        mclist0 = mclist0.filter(tags__name__in=mc_search_tag_list).order_by().distinct()

    mclist = mclist0
    all_tag_list = list(Tag.objects.all())

    context = {
        'mclist': mclist,
        'all_tag_list': all_tag_list,
        'mc_search_name': mc_search_name,
        'mc_search_tag': mc_search_tag
    }
    return render(request, 'wedding/mc_list.html', context)


def wedding_cast(request):
    if request.method == 'POST':
        castform = CastForm(request.POST)
        if castform.is_valid():
            castformquestion = castform.save(commit=False)
            castformquestion.create_date = timezone.now()
            castformquestion.save()
            return redirect('wedding:wedding_cast_success')
    elif request.method == 'GET':
        mc_cast_name = request.GET.get('mc_cast_name','')
        castform = CastForm()
        get_context = {
            'wish_mc': mc_cast_name,
            'castform': castform
        }
        return render(request, 'wedding/cast.html', get_context)
    else:
        castform = CastForm()
    context = {'castform': castform}
    return render(request, 'wedding/cast.html', context)


def wedding_cast_success(request):
    return render(request, 'wedding/cast_success.html')


def partners(request):
    return render(request, 'wedding/partners_etland.html')

templates/base.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
        crossorigin="anonymous"
    />
    <link
        href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
        rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'cssjs/customization.css' %}" />
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!-- 상단 메뉴 시작 -->
<div id="topper" class="fixed-top">
    <img src="/static/images/annport_logo_small.svg" alt="" width="70px;" style="margin: 0 10px 1px 0">
    <span>웨딩 | 에이전시 | 아카데미</span>
</div>
{% block navbar %}{% endblock %}
<div id="top_spacer"></div>
<!-- 상단 메뉴 끝 -->

<!-- Contents 시작 -->
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<!-- Contents 끝 -->

<!-- Footer 시작 -->
<div id="footer" class="clearfix">
    <div class="container">
        <div class="p-3" style="color: #afb5bf">
            <img class="my-3" src="/static/images/annport_logo_simple.svg" alt="" width="120px"/>
            <br />
            <p class="ps-4">
                아나포트 <br />
                박종근 <br />
                서울 강서구 공항대로 45길 44 청림빌딩 414호 <br />
                사업자등록번호: 109-16-43122 (박종근)
                <br />
                전화번호: 02-3663-0947 / 010-9091-0947 <br />
                팩스: 02-6442-9091
            </p>
        </div>
    </div>
</div>
<!-- Footer 끝 -->

<script src="{% static 'cssjs/jquery-3.6.0.min.js' %}"></script>
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"
></script>
<script src="https://unpkg.com/boxicons@2.0.9/dist/boxicons.js"></script>
{% block script %}{% endblock %}
</body>
</html>

templates/wedding/cast_success.html
{% extends "base.html" %}

{% block head %}

{% endblock %}

{% block title %}
    ANNPORT Wedding : 섭외 문의
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}
<div class="container pt-5">
    <div class="m-3 p-5 justify-content-center align-content-center border border-dark" style="text-align: center; border-radius: 10px;">
        <div>작성하신 내용으로 전송되었습니다. 확인 후 아나포트 담당자가 연락드리겠습니다.</div><br>
        <div>감사합니다 :)</div><br>
        <div>
            <a href="{% url 'wedding:wedding_list' %}" type="button" class="btn btn-dark">사회자 목록으로 돌아갑니다.</a>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

templates/wedding/home.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<meta name="naver-site-verification" content="0e5a977b38d35d06726e8246ac3308bc5f4a0d46" />
{% endblock %}

{% block title %}
    ANNPORT Wedding
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}
    <div class="container" style="position: relative">
        <div style="position: absolute; z-index: 10; right: 30px; top: 30px;">
            <a href="{% url 'wedding:partners' %}">
                <img src="{% static 'images/sponsor/etland_banner.png' %}" style="width: 250px;">
            </a>
        </div>
    </div>
    <div id="fullcover">
        <div id="carouselwrap" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for home in homepage %}
                <div class="carousel-item home_content {% if forloop.counter == 1 %}active{% endif %}"
                        style="background: url('{{ home.main_backdrop.url }}');
                                {% if home.text_color_dark %}color: black;{% else %}color: white;{% endif %}">
                    {% if home.back_panel %}
                        <div class="back_panel"
                             style="{% if home.text_color_dark %}background-color: #ffffff66;{% else %}background-color: #00000066;{% endif %}">
                    {% endif %}
                    <div class="home_sub_title">
                        {{ home.sub_title | linebreaks }}
                    </div>
                    <div class="home_title" style="{% if home.title_color %}color:{{ home.title_color }};{% endif %}">
                        {{ home.title | linebreaks }}
                    </div>
                    <div class="home_description">
                        {{ home.description | linebreaks }}
                    </div>
                    {% if home.buttons_text|length > 0 and home.buttons_url|length > 0 %}
                        <a href="{{ home.buttons_url }}" type="button" class="btn home_button">
                        {{ home.buttons_text }}
                        </a>
                    {% endif %}
                    {% if home.back_panel %}</div>{% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script>
const fullcover = document.getElementById('fullcover')
console.log(window.innerHeight)
fullcover.style.height = (window.innerHeight) - 100
window.addEventListener('resize', (e) => {
    fullcover.style.height = (window.innerHeight) - 100
});
</script>

{% endblock %}

templates/wedding/mc_detail.html
{% extends "base.html" %}
{% load templatetags %}

{% block head %}

{% endblock %}

{% block title %}
    ANNPORT Wedding : 사회자 상세
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center align-items-end" id="profile_portrait"
             style="background-image: url('{{ mc.profile_backdrop.image.url }}');"
        >
            <img id="profile_portrait_img" src="{{ mc.profile_photo.url}}" alt="" />
        </div>
        <div id="profile_overlay" class="p-1">
            <h5>{{ mc.title }}</h5>
            <h1 id="mc_name_text">{{ mc.name }}</h1>
            <div class="mx-auto" style="margin-top: 35px; width: 30px; height: 5px; background-color: black;"></div>
        </div>
    </div>

    <!-- #상세내용 시작 -->
    <div class="container text-center">
        <!-- 태그 -->
        <div class="d-flex justify-content-center">
            <div class="row gx-2 row-cols-3 justify-content-center" style="max-width: 400px;">
                {% for tag in tag_list %}
                    <div class="col-auto">
                        <div class="px-3 py-2 my-1 text-light" style="background-color: #f6895b">
                            <span>#{{ tag }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- 설명 -->
        <div id="profile_description" class="my-3 mx-auto">
            {{ mc.description }}
        </div>

        <!-- 기능아이콘 -->
        <div class="row gx-2 row-cols-lg-3 justify-content-center">
                <button class="btn btn-primary call_btn" id="cast_btn"><span style="font-size: 1.2em;">섭외 문의</span></button>
        </div>

        <!-- 추가정보 -->
        <div id="profile_more" class="row">
            <!-- 갤러리 -->
            <div class="col-12 col-lg-8 mb-5 mb-lg-3">
                <div id="movies_carousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
                    <!-- 이미지들 -->
                    <div class="carousel-inner">
                        {% if mc.youtube_set.count > 0 %}
                            {% for youtube in mc.youtube_set.all %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <div class="youtube-embed d-block w-100 ratio ratio-16x9">
                                        <iframe
                                            src="https://www.youtube-nocookie.com/embed/{{ youtube.url }}?rel=0"
                                            frameborder="0"
                                            allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                            allowfullscreen
                                        ></iframe>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <!-- 썸네일 -->
                    <div class="carousel_thumbnails d-flex flex-wrap justify-content-start mt-2 gap-1">
                        {% if mc.youtube_set.count > 0 %}
                            {% for youtube in mc.youtube_set.all %}
                                <div class="carousel_thumbnail00">
                                    <img
                                        src="https://img.youtube.com/vi/{{ youtube.url }}/mqdefault.jpg"
                                        type="button"
                                        data-bs-target="#movies_carousel"
                                        data-bs-slide-to="{{ forloop.counter0 }}"
                                        aria-label="Slide {{ forloop.counter }}"
                                        aria-current="true"
                                        class="active rounded"
                                    />
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>

            <!-- 이력 등 -->
            <div id="profile_career" class="col-12 col-lg-4 text-start px-4">
                {{ mc.profile|mark }}
            </div>
        </div>
    </div>
    <!-- 상세내용 끝 -->

    <form id="cast_form" method="get" action="{% url 'wedding:wedding_cast' %}">
        <input type="hidden" id="mc_cast_name" name="mc_cast_name" value="{{ mc_cast_name|default_if_none:'' }}">
    </form>
{% endblock %}

{% block script %}
<script>
const mc_name = document.getElementById('mc_name_text')
let mc_cast_name = document.getElementById('mc_cast_name')

document.addEventListener('DOMContentLoaded', (event) => {
    mc_cast_name.value = mc_name.textContent.trim()
});

const cast_btn = document.getElementById('cast_btn')
const cast_form = document.getElementById('cast_form')

cast_btn.addEventListener('click', mcCast)
function mcCast(e) {
    cast_form.submit();
}
</script>
{% endblock %}

templates/wedding/mc_list.html
{% extends "base.html" %}

{% block head %}

{% endblock %}

{% block title %}
    ANNPORT Wedding : 소속 사회자
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}
    <!-- 진행자 열람창 -->
    <div class="container my-5 pt-5">
        <div class="px-2 d-inline">
            {% if mc_search_name or mc_search_tag %}
                <a href="{% url "wedding:wedding_list" %}">
                <span class="badge rounded-pill text-dark mc_tag_reset_btn">검색결과 초기화</span>
                </a>
                <span class="badge bg-secondary">{{ mc_search_name }}</span>
                <span class="badge bg-secondary">{{ mc_search_tag }}</span>
                <span style="font-size: 0.8em;">의 검색결과</span>
            {% endif %}
        </div>
        <div class="row pt-4">
            <!-- 진행자 검색 및 태그 선택 -->
            <div class="col-12 col-lg-4 mb-5">
                <div class="mb-2">
                    <input
                            id="mc_finder"
                            class="form-control form-control-lg"
                            type="text"
                            placeholder="진행자의 이름으로 검색하세요."
                            value="{{ mc_search_name|default_if_none:'' }}"
                    />
                </div>

                <div id="mc_tag_selector">
                    <div class="py-2 px-3 mb-1" id="mc_tag_selector_desc">
                        <i class="bx bxs-down-arrow"></i>
                        <span>원하시는 진행자 이미지를 선택하세요.</span>
                    </div>
                    <div id="mc_tag_reset">
                        <span class="badge rounded-pill text-dark mc_tag_reset_btn" onclick="unselect_button()">
                            태그 초기화
                        </span>
                        <!--
                        <div id="mc_tag_reset_btn" onclick="unselect_button()">태그 초기화</div>  -->                   </div>
                    <div id="mc_tag_list" class="d-flex flex-wrap justify-content-start">
                        {% for tag in all_tag_list %}
                        <a href="#" class="btn btn-sm search_check"
                           id="search_check_{{ forloop.counter0 }}" name="search_check_{{ forloop.counter0 }}"
                           role="button" data-bs-toggle="button">#{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="d-grid gap-2 mt-3">
                    <button class="btn btn-dark search_btn" id="search_btn">
                        <i
                                class="bx bx-search bx-sm"
                                style="color: white; padding: 0 5px"
                        ></i>
                        <span>검색</span>
                    </button>
                </div>
            </div>

            <!-- 진행자 목록 -->
            <div class="col-12 col-lg-8">
                <div id="mc_grid">
                    {% if mclist.exists %}
                        {% for mc in mclist %}
                            <div class="mc_card" onclick="location.href='{% url "wedding:wedding_detail" mc.id %}'" style="background-image: url('{{ mc.profile_backdrop.image.url }}');">
                                <img class="mc_card_image" src='{{ mc.profile_photo.url }}'>
                                <div class="mc_card_overlay py-2">
                                    <h6>{{ mc.name }} {{ mc.title }}</h6>
                                    <span class="d-block text-truncate">{% for mctag in mc.tags.all %}#{{ mctag }} {% endfor %}</span>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div id="no_mc">
                            조건에 맞는 결과가 없습니다. <br>
                            조건을 바꿔 다시 검색해주세요.
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <form id="search_form" method="get" action="{% url 'wedding:wedding_list' %}">
        <input type="hidden" id="mc_search_name" name="mc_search_name" value="{{ mc_search_name|default_if_none:'' }}">
        <input type="hidden" id="mc_search_tag" name="mc_search_tag" value="{{ mc_search_tag|default_if_none:'' }}">
    </form>
{% endblock %}

{% block script %}
<script>
const search_input = document.getElementById('mc_finder')
const tag_buttons = document.querySelectorAll('.search_check')
const search_btn = document.getElementById('search_btn')
const search_form = document.getElementById('search_form')
let mc_search_name = document.getElementById('mc_search_name')
let mc_search_tag = document.getElementById('mc_search_tag')

document.addEventListener('DOMContentLoaded', (event) => {
    let tags_list = mc_search_tag.value.split(',')
    tag_buttons.forEach(function (button) {
        for (let i in tags_list) {
            if(button.textContent.substring(1).trim() === tags_list[i] ) {
                button.setAttribute('aria-pressed', "true")
                button.classList.add("active")
            }
        }
    })
});

function unselect_button() {
    tag_buttons.forEach(function (button) {
        if(button.getAttribute('aria-pressed') === "true"){
            button.setAttribute('aria-pressed', "false")
            button.classList.remove("active")
        }
    })
}

search_btn.addEventListener('click', mcSearch)
function mcSearch(e) {
    let mc_search_tag_list = []
    mc_search_name.value = search_input.value
    tag_buttons.forEach(function (button) {
        if(button.getAttribute('aria-pressed') === "true"){
            mc_search_tag_list.push(button.textContent.substring(1).trim())
            button.setAttribute('aria-pressed', "false")
            button.classList.remove("active")
        }
    })
    mc_search_tag.value = mc_search_tag_list
    search_form.submit();
}
</script>
{% endblock %}

templates/wedding/navbar.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top p-0 ann_nav ann_nav_wedding">
    <div class="container">
        <a class="navbar-brand" href="{% url 'wedding:wedding_index' %}">
            <div class="ann_logo_wrap">
                <div>
                    <img class="ann_logo_wedding" src="/static/images/annwedding_logo.svg" alt="" width="200px">
                </div>
            </div>
        </a>
        <button
                class="navbar-toggler border-0"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <box-icon name="menu" size="md"></box-icon>
        </button>
        <div class="collapse navbar-collapse align-self-end justify-content-end mb-2" id="navbarNav">
            <ul class="navbar-nav">
                <!-- 현재 페이지 <a class="nav-link active" aria-current="page" href="#"> -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wedding:wedding_service' %}">아나포트 웨딩 서비스</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wedding:wedding_list' %}">소속 사회자</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wedding:wedding_cast' %}">섭외 문의</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wedding:partners' %}">제휴 혜택</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/wedding/partners_etland.html
{% extends "base.html" %}
{% load static %}

{% block head %}

{% endblock %}

{% block title %}
    ANNPORT Wedding X 전자랜드
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}
     <div class="container p-0" style="max-width: 800px;">
        <div>
            <img src="{% static 'images/sponsor/etland_content_1.png' %}" style="max-width: 100%">
            <img src="{% static 'images/sponsor/etland_content_2.png' %}" style="max-width: 100%">
            <img src="{% static 'images/sponsor/etland_content_3.png' %}" style="max-width: 100%">
            <img src="{% static 'images/sponsor/etland_content_4.png' %}" style="max-width: 100%">
        </div>
         <div class="my-3 justify-content-end text-end">
             <img src="{% static 'images/sponsor/etland_qr.jpg' %}" style="width: 100%; max-width: 200px;">
         </div>
     <!-- QR코드 -->
     </div>

{% endblock %}

{% block script %}

{% endblock %}

templates/wedding/wedding_preset.html
{% extends "base.html" %}

{% block head %}

{% endblock %}

{% block title %}
    ANNPORT Wedding :
{% endblock %}

{% block navbar %}
    {% include "wedding/navbar.html" %}
{% endblock %}

{% block content %}

{% endblock %}

{% block script %}

{% endblock %}